# Generated by Django 3.1.3 on 2020-11-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transform', '0003_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='trans',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=70)),
                ('plan', models.CharField(default='', max_length=500)),
                ('gender', models.CharField(default='', max_length=500)),
                ('transformation', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
