# Generated by Django 3.1.3 on 2020-11-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transform', '0004_trans'),
    ]

    operations = [
        migrations.AddField(
            model_name='trans',
            name='age',
            field=models.CharField(default='', max_length=70),
        ),
    ]
