# Generated by Django 3.1.3 on 2020-11-19 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transform', '0005_trans_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='trans',
            new_name='Client',
        ),
    ]
