# Generated by Django 3.1.3 on 2020-11-19 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transform', '0006_auto_20201119_1900'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blog',
        ),
    ]
